blank_issues_enabled: false
contact_links:
  - name: QQ群
    url: https://jq.qq.com/?_wv=1027&k=mtvdUuor
    about: '加入小助手官方Bug测试群: 747753199'

  - name: Discord频道
    url: https://discord.gg/7GuNzajfhD
    about: '加入小助手官方Discord频道'
